/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Coursework;

import java.io.FileNotFoundException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import java.time.format.DateTimeFormatter;
import java.time.LocalDateTime;
import java.util.List;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author lenovo
 */
public class Cabservice extends javax.swing.JFrame {
List <greencabs> green= new ArrayList<greencabs>();


int ro;
    /**
     * Creates new form Cabservice
     */
    public Cabservice() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GREENWICH_CABS");

        panel1.setFont(new java.awt.Font("Georgia", 3, 10)); // NOI18N
        panel1.setForeground(new java.awt.Color(204, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sam", "Alex", "Rudolf", "Henry", " ", " " }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        panel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 100, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setLabel("Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 70, -1));

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 70, 20));

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 100, -1));

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 100, -1));

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 100, -1));

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        panel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 100, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Connecting London");
        jLabel2.setAutoscrolls(true);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 470, -1));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 199, 48));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("StartTime");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 20));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 202, 49));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pickup Point");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, 20));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 179, 49));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Destination");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 20));

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 176, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Telephone");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 100, 20));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 202, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Driver");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 90, 20));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 176, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Passenger");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 20));

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 100, -1));

        jLabel8.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 176, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Account");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 100, 20));

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField6FocusGained(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel1.getAccessibleContext().setAccessibleName("Greenwich CABS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int flag =validation();
      if(flag==1)
      {
      adddata();
      String dt=id();
      String dp = "The ID is : " + dt+". Below Details has been saved, Do you want to add more? ";
      int response = JOptionPane.showConfirmDialog(null,dp, "Confirm", JOptionPane.YES_NO_OPTION);
      clear();
      if(response==JOptionPane.NO_OPTION) 
      {
           int rp = JOptionPane.showConfirmDialog(null,"Do you want to add the completed work details?", "Confirm", JOptionPane.YES_NO_OPTION);
           if(rp==JOptionPane.YES_OPTION) 
      {
          do
          {
          String Title = "TravelID";
          String fd = JOptionPane.showInputDialog(null,"Enter the Travel ID", Title, 2);
          travel(fd);
          ro = JOptionPane.showConfirmDialog(null,"Do you want to add more completed work details?", "Confirm", JOptionPane.YES_NO_OPTION);
      }while(ro==JOptionPane.YES_OPTION);
          }
           ro = JOptionPane.showConfirmDialog(null,"Do you want to write the data into the file 'date.txt'");
            if(ro==JOptionPane.YES_OPTION)
            {
             JOptionPane.showMessageDialog(null, "Printing the JTable and writing the file");
                calc();   
                System.out.println("Written file");
                String filename =getFileName() + ".txt";
               PrintWriter opfile = null; 
                try {
                    
                    opfile = new PrintWriter(filename);
                   
                } catch (FileNotFoundException ex) {
                    System.out.println(ex);
                    Logger.getLogger(Cabservice.class.getName()).log(Level.SEVERE, null, ex);
                }
                String name = "Time" +" | "+"Pickup point"+" | "+"Destination"+" | "+"Passenger"+"|"+" Driver"+" | "+ "Amount" + " | "+ "Account" +" | " + "Telephone";
                opfile.println(name);
         for(greencabs gre:green)
        {
            opfile.println("  ");
            String output= gre.time + " | " +gre.ppoint + " | " +gre.dest +" | "+gre.pngr+" | "+gre.drvr+" | "+gre.amt+" | "+gre.accnt+" | "+gre.tphn;
            opfile.println(output);
        }
         opfile.close();
            }   
      }
      }
     
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if(jTextField1.getText().equals(" "))
        {
            jTextField1.setText("");
        }
        else{
            jTextField1.selectAll();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
       if(jTextField2.getText().equals(" "))
        {
            jTextField2.setText("");
        }
        else{
            jTextField2.selectAll();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained
       if(jTextField3.getText().equals(" "))
        {
            jTextField3.setText("");
        }
        else{
            jTextField3.selectAll();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
       if(jTextField4.getText().equals(" "))
        {
            jTextField4.setText("");
        }
        else{
            jTextField4.selectAll();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int response = JOptionPane.showConfirmDialog(null,"Do you want to undo the selection done?", "Confirm", JOptionPane.YES_NO_OPTION);
      if(response==JOptionPane.YES_OPTION) 
      {
        clear();
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6FocusGained

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    /**
     * @param args the command line arguments
     */
  //  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    public static void main(String args[]) 
    {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cabservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cabservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cabservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cabservice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Cabservice().setVisible(true);
            }
        });
    }
    public void travel(String id)
    {
        float endtime,time;
        double amount;
        for(greencabs gre:green)
        {
       if(gre.getDt().contentEquals(id))
         {
          String et = JOptionPane.showInputDialog(null, "Enter the end time of journey");
          endtime= Float.parseFloat(et);
          time = gre.getTime();
          System.out.println("Endtime " +endtime);
          amount = 20*(endtime - time - (endtime -time)* 0.4);
          gre.setAmt(amount);
          }     
           }
    }
    public void adddata()
    {  
      greencabs gre = new greencabs();
      gre.setTime(Float.parseFloat(jTextField1.getText()));
      gre.setPpoint(jTextField2.getText());
      gre.setDest(jTextField3.getText());
      gre.setDrvr((String)jComboBox1.getSelectedItem());
      gre.setPngr(jTextField5.getText());
      gre.setAccnt(jTextField6.getText());
      gre.setTphn(Long.parseLong(jTextField4.getText()));
      String dt = id() ;
      gre.setDt(dt);
      green.add(gre);
      }
    
    public String id()
    {
      String dt;
      DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyyMMddHHmm");
      LocalDateTime ld= LocalDateTime.now();
      dt=ld.format(dtf);
      return(dt);
    }
    public int  validation()
    {
        int flag =0;
        float numb;
        int num,rem;
        numb = Float.parseFloat(jTextField1.getText());
        numb =numb*100;
        num=(int) (numb/100);
        rem =(int)(numb%100);
        if(num>23||rem>59)
        {
            JOptionPane.showMessageDialog(null, "Enter a valid time");
        }
       else if(jTextField2.getText().isEmpty()||jTextField1.getText().isEmpty()||jTextField3.getText().isEmpty()||jTextField5.getText().isEmpty())
        {
           JOptionPane.showMessageDialog(null, "Please fill all the values, All fields are mandatory"); 
        }
       else if(jTextField2.getText().equals(" ")||jTextField1.getText().equals(" ")||jTextField3.getText().equals(" ")||jTextField5.getText().equals(" "))
        {
           JOptionPane.showMessageDialog(null, "Please fill all the values, All fields are mandatory"); 
        }
        else
        {
            flag=1;
        }
        return(flag);
    }
    
    public String getFileName() {
         String dt;
      DateTimeFormatter dtf= DateTimeFormatter.ofPattern("yyyyMMdd");
      LocalDateTime ld= LocalDateTime.now();
      dt=ld.format(dtf);
      return(dt);
    }
    
    public void clear()
    {
       jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null); 
        jTextField5.setText(null); 
        jTextField6.setText(null); 
    }
    
    
    public void calc()
    {
        DisplayOfDay dd= new DisplayOfDay();
        double sum =0;
        float count =0;
        for(greencabs gre:green)
        {
           gre.display();
          sum = sum+gre.amt;
          dd.setTotal(sum);
            switch (gre.drvr) {
                case "Sam" -> {
                    dd.amt[0]+=gre.amt;
                    dd.count[0]++;
                }
                case "Alex" -> {
                    dd.amt[1]+=gre.amt;
                    dd.count[1]++;
                }
                case "Rudolf" -> {
                    dd.amt[2]+=gre.amt;
                    dd.count[2]++;
                }
                default -> {
                    dd.amt[3]+=gre.amt;
                    dd.count[3]++;
                }
            }
            count++;
            dd.setJobs(count);
        }
        dd.getdata();
        dd.display();
        dd.setVisible(true);
        this.setVisible(false);
    }
    
    
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
